### ISSUE TITLE
There should be a way to store the fetched data in cache

### ISSUE THREAD

**Issue by pinterid** [snek-at/front-legacy#112]
**Is your feature request related to a problem? Please describe.**
Currently the fetched data is not stored anywhere and login process takes forever.

**Describe the solution you'd like**
On the regristration, the data of a user should be fetched and stored in the cache. On a login the data is pulled from the cache and the fetching process runs again in background.

**Additional context**
- Ref: https://de.wikipedia.org/wiki/Cache

**Comment by kleberbaum** [comment]
This issue has been reopened due to issue #143.
