### ISSUE TITLE
There should be a way to view the active tab

### ISSUE THREAD

**Issue by pinterid** [snek-at/front-legacy#121]
**Is your feature request related to a problem? Please describe.**
Currently the active tab is not highlighted.

**Describe the solution you'd like**
The active tab should be highlighted using a style that differs from the other tabs.

**Comment by Aichnerc** [comment]
This is a bug related to MDB and react-router-dom: https://mdbootstrap.com/support/react/tab-navigation-always-active/
 A workaround has been implemented.

**Comment by kleberbaum** [comment]
This issue has been reopened due to issue #143.
